name = "VivaRP"
author = "by_lowix"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "000c5172dc98c0aa18c6c8ae3c7a614511b2b7fc2ab7ec344346044d1e28ebd5"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
