name = "VivaRP"
author = "by_lowix"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd54c599556a1e4367790e8b7ab3d9b32c6f1e4002201c7414e6d810675c0bae"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
