name = "VivaRP"
author = "by_lowix"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0127e0be37838ee7e3700698cb6d0f893686b6a6f2170040b8ca4d52b50838ba"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
