textures.1=2 3
biomes.1=bamboo_jungle jungle sparse_jungle savanna savanna_plateau

textures.2=2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 20 21
biomes.2=flower_forest

textures.3=13 15 16 17 20
biomes.3=birch_forest old_growth_birch_forest

textures.4=2 3 4 6 6 9 10 11 12
biomes.4=plains

textures.5=18
biomes.5=sunflower_plains

textures.6=13 15 16 17
biomes.6=dark_forest

textures.7=14
biomes.7=eroded_badlands wooded_badlands badlands desert

textures.8=5
biomes.8=swamp

textures.9=2 3 4 6 7 12 20
biomes.9=meadow

textures.10=22
biomes.10=pale_garden

textures.11=19
biomes.11=cherry_grove

textures.12=21
biomes.12=lush_caves

textures.13=23
biomes.13=deep_dark

textures.14=24
biomes.14=dappled_forest

textures.15=13 15 16 17
biomes.15=forest